version: '3.1'
services:
  app:
    container_name: SecondLabSpring
    image: tomcat_server_with_second_lab
    environment:
      profile: docker
    build:
      context: .
    ports:
      - "8888:8080"
    depends_on:
      - postgresqldb
  smart-adder:
    container_name: SmartAdderService
    image: smart_adder_service
    environment:
      profile: docker
    build:
      dockerfile: smart-adder.dockerfile
      context: C:/Users/Home-PC/IdeaProjects/BookInfoService
    ports:
      - "8889:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgresqldb
    image: postgresforsecondlab
    build:
      context: .
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=lab2
      - POSTGRES_PASSWORD=zsecsq
      - POSTGRES_USER=postgres
volumes:
  postgresvolume:
    external: true