CREATE TABLE IF NOT EXISTS users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    login character varying(255),
    password character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    role character varying(255),
    status character varying(255) ,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_login UNIQUE (login)
);
GO